package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="insaforp"
)
public class Curso  implements java.io.Serializable {


     private int idCurso;
     private Curso curso;
     private Local local;
     private Programa programa;
     private Proveedor proveedor;
     private String nombreCurso;
     private String descripcionCurso;
     private Boolean estadoCurso;
     private Integer duracionHoras;
     private String requisitos;
     private Integer cupo;
     private Date fechaCreacion;
     private Date fechaInicioInscripcion;
     private Date fechaFinInscripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private Set<Presupuesto> presupuestos = new HashSet<Presupuesto>(0);
     private Set<Curso> cursos = new HashSet<Curso>(0);
     private Set<IncripcionCurso> incripcionCursos = new HashSet<IncripcionCurso>(0);

    public Curso() {
    }

	
    public Curso(int idCurso) {
        this.idCurso = idCurso;
    }
    public Curso(int idCurso, Curso curso, Local local, Programa programa, Proveedor proveedor, String nombreCurso, String descripcionCurso, Boolean estadoCurso, Integer duracionHoras, String requisitos, Integer cupo, Date fechaCreacion, Date fechaInicioInscripcion, Date fechaFinInscripcion, Date fechaInicio, Date fechaFin, Set<Presupuesto> presupuestos, Set<Curso> cursos, Set<IncripcionCurso> incripcionCursos) {
       this.idCurso = idCurso;
       this.curso = curso;
       this.local = local;
       this.programa = programa;
       this.proveedor = proveedor;
       this.nombreCurso = nombreCurso;
       this.descripcionCurso = descripcionCurso;
       this.estadoCurso = estadoCurso;
       this.duracionHoras = duracionHoras;
       this.requisitos = requisitos;
       this.cupo = cupo;
       this.fechaCreacion = fechaCreacion;
       this.fechaInicioInscripcion = fechaInicioInscripcion;
       this.fechaFinInscripcion = fechaFinInscripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.presupuestos = presupuestos;
       this.cursos = cursos;
       this.incripcionCursos = incripcionCursos;
    }
   
     @Id 

    
    @Column(name="id_curso", unique=true, nullable=false)
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cur_id_curso")
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_local")
    public Local getLocal() {
        return this.local;
    }
    
    public void setLocal(Local local) {
        this.local = local;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_programa")
    public Programa getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(Programa programa) {
        this.programa = programa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proveedor")
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    
    @Column(name="nombre_curso", length=100)
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }

    
    @Column(name="descripcion_curso", length=200)
    public String getDescripcionCurso() {
        return this.descripcionCurso;
    }
    
    public void setDescripcionCurso(String descripcionCurso) {
        this.descripcionCurso = descripcionCurso;
    }

    
    @Column(name="estado_curso")
    public Boolean getEstadoCurso() {
        return this.estadoCurso;
    }
    
    public void setEstadoCurso(Boolean estadoCurso) {
        this.estadoCurso = estadoCurso;
    }

    
    @Column(name="duracion_horas")
    public Integer getDuracionHoras() {
        return this.duracionHoras;
    }
    
    public void setDuracionHoras(Integer duracionHoras) {
        this.duracionHoras = duracionHoras;
    }

    
    @Column(name="requisitos", length=200)
    public String getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(String requisitos) {
        this.requisitos = requisitos;
    }

    
    @Column(name="cupo")
    public Integer getCupo() {
        return this.cupo;
    }
    
    public void setCupo(Integer cupo) {
        this.cupo = cupo;
    }
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @Column(name="fecha_creacion", length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @Column(name="fecha_inicio_inscripcion", length=10)
    public Date getFechaInicioInscripcion() {
        return this.fechaInicioInscripcion;
    }
    
    public void setFechaInicioInscripcion(Date fechaInicioInscripcion) {
        this.fechaInicioInscripcion = fechaInicioInscripcion;
    }
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @Column(name="fecha_fin_inscripcion", length=10)
    public Date getFechaFinInscripcion() {
        return this.fechaFinInscripcion;
    }
    
    public void setFechaFinInscripcion(Date fechaFinInscripcion) {
        this.fechaFinInscripcion = fechaFinInscripcion;
    }
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @Column(name="fecha_inicio", length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @Column(name="fecha_fin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set<Presupuesto> getPresupuestos() {
        return this.presupuestos;
    }
    
    public void setPresupuestos(Set<Presupuesto> presupuestos) {
        this.presupuestos = presupuestos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set<IncripcionCurso> getIncripcionCursos() {
        return this.incripcionCursos;
    }
    
    public void setIncripcionCursos(Set<IncripcionCurso> incripcionCursos) {
        this.incripcionCursos = incripcionCursos;
    }
    



}


