package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * DetalleFinanciamiento generated by hbm2java
 */
@Entity
@Table(name="detalle_financiamiento"
    ,catalog="insaforp"
)
public class DetalleFinanciamiento  implements java.io.Serializable {


     private int idDetalleFinanciamieto;
     private Financiamiento financiamiento;
     private Presupuesto presupuesto;
     private BigDecimal monto;
     private Date fechaRegistro;

    public DetalleFinanciamiento() {
    }

	
    public DetalleFinanciamiento(int idDetalleFinanciamieto, Financiamiento financiamiento, Presupuesto presupuesto) {
        this.idDetalleFinanciamieto = idDetalleFinanciamieto;
        this.financiamiento = financiamiento;
        this.presupuesto = presupuesto;
    }
    public DetalleFinanciamiento(int idDetalleFinanciamieto, Financiamiento financiamiento, Presupuesto presupuesto, BigDecimal monto, Date fechaRegistro) {
       this.idDetalleFinanciamieto = idDetalleFinanciamieto;
       this.financiamiento = financiamiento;
       this.presupuesto = presupuesto;
       this.monto = monto;
       this.fechaRegistro = fechaRegistro;
    }
   
     @Id 

    
    @Column(name="id_detalle_financiamieto", unique=true, nullable=false)
    public int getIdDetalleFinanciamieto() {
        return this.idDetalleFinanciamieto;
    }
    
    public void setIdDetalleFinanciamieto(int idDetalleFinanciamieto) {
        this.idDetalleFinanciamieto = idDetalleFinanciamieto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_financiamiento", nullable=false)
    public Financiamiento getFinanciamiento() {
        return this.financiamiento;
    }
    
    public void setFinanciamiento(Financiamiento financiamiento) {
        this.financiamiento = financiamiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_presupuesto", nullable=false)
    public Presupuesto getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(Presupuesto presupuesto) {
        this.presupuesto = presupuesto;
    }

    
    @Column(name="monto", precision=7)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @DateTimeFormat(pattern="yyyy-MM-dd")
    @Column(name="fecha_registro", length=10)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }



}


