package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleGasto generated by hbm2java
 */
@Entity
@Table(name="detalle_gasto"
    ,catalog="insaforp"
)
public class DetalleGasto  implements java.io.Serializable {


     private int idDetalleGasto;
     private Gasto gasto;
     private Presupuesto presupuesto;
     private BigDecimal monto;
     private Date fechaRegistro;

    public DetalleGasto() {
    }

	
    public DetalleGasto(int idDetalleGasto, Gasto gasto, Presupuesto presupuesto) {
        this.idDetalleGasto = idDetalleGasto;
        this.gasto = gasto;
        this.presupuesto = presupuesto;
    }
    public DetalleGasto(int idDetalleGasto, Gasto gasto, Presupuesto presupuesto, BigDecimal monto, Date fechaRegistro) {
       this.idDetalleGasto = idDetalleGasto;
       this.gasto = gasto;
       this.presupuesto = presupuesto;
       this.monto = monto;
       this.fechaRegistro = fechaRegistro;
    }
   
     @Id 

    
    @Column(name="id_detalle_gasto", unique=true, nullable=false)
    public int getIdDetalleGasto() {
        return this.idDetalleGasto;
    }
    
    public void setIdDetalleGasto(int idDetalleGasto) {
        this.idDetalleGasto = idDetalleGasto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_gasto", nullable=false)
    public Gasto getGasto() {
        return this.gasto;
    }
    
    public void setGasto(Gasto gasto) {
        this.gasto = gasto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_presupuesto", nullable=false)
    public Presupuesto getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(Presupuesto presupuesto) {
        this.presupuesto = presupuesto;
    }

    
    @Column(name="monto", precision=7)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_registro", length=10)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


