package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Financiamiento generated by hbm2java
 */
@Entity
@Table(name="financiamiento"
    ,catalog="insaforp"
)
public class Financiamiento  implements java.io.Serializable {


     private int idFinanciamiento;
     private String nombreFinanciamiento;
     private Set<DetalleFinanciamiento> detalleFinanciamientos = new HashSet<DetalleFinanciamiento>(0);

    public Financiamiento() {
    }

	
    public Financiamiento(int idFinanciamiento) {
        this.idFinanciamiento = idFinanciamiento;
    }
    public Financiamiento(int idFinanciamiento, String nombreFinanciamiento, Set<DetalleFinanciamiento> detalleFinanciamientos) {
       this.idFinanciamiento = idFinanciamiento;
       this.nombreFinanciamiento = nombreFinanciamiento;
       this.detalleFinanciamientos = detalleFinanciamientos;
    }
   
     @Id 

    
    @Column(name="id_financiamiento", unique=true, nullable=false)
    public int getIdFinanciamiento() {
        return this.idFinanciamiento;
    }
    
    public void setIdFinanciamiento(int idFinanciamiento) {
        this.idFinanciamiento = idFinanciamiento;
    }

    
    @Column(name="nombre_financiamiento", length=50)
    public String getNombreFinanciamiento() {
        return this.nombreFinanciamiento;
    }
    
    public void setNombreFinanciamiento(String nombreFinanciamiento) {
        this.nombreFinanciamiento = nombreFinanciamiento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="financiamiento")
    public Set<DetalleFinanciamiento> getDetalleFinanciamientos() {
        return this.detalleFinanciamientos;
    }
    
    public void setDetalleFinanciamientos(Set<DetalleFinanciamiento> detalleFinanciamientos) {
        this.detalleFinanciamientos = detalleFinanciamientos;
    }




}


