package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gasto generated by hbm2java
 */
@Entity
@Table(name="gasto"
    ,catalog="insaforp"
)
public class Gasto  implements java.io.Serializable {


     private int idGasto;
     private String nombreGasto;
     private Set<DetalleGasto> detalleGastos = new HashSet<DetalleGasto>(0);

    public Gasto() {
    }

	
    public Gasto(int idGasto) {
        this.idGasto = idGasto;
    }
    public Gasto(int idGasto, String nombreGasto, Set<DetalleGasto> detalleGastos) {
       this.idGasto = idGasto;
       this.nombreGasto = nombreGasto;
       this.detalleGastos = detalleGastos;
    }
   
     @Id 

    
    @Column(name="id_gasto", unique=true, nullable=false)
    public int getIdGasto() {
        return this.idGasto;
    }
    
    public void setIdGasto(int idGasto) {
        this.idGasto = idGasto;
    }

    
    @Column(name="nombre_gasto", length=50)
    public String getNombreGasto() {
        return this.nombreGasto;
    }
    
    public void setNombreGasto(String nombreGasto) {
        this.nombreGasto = nombreGasto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gasto")
    public Set<DetalleGasto> getDetalleGastos() {
        return this.detalleGastos;
    }
    
    public void setDetalleGastos(Set<DetalleGasto> detalleGastos) {
        this.detalleGastos = detalleGastos;
    }




}


