package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * IncripcionCurso generated by hbm2java
 */
@Entity
@Table(name="incripcionCurso"
    ,catalog="insaforp"
)
public class IncripcionCurso  implements java.io.Serializable {


     private int idInscripcion;
     private Curso curso;
     private Participante participante;
     private Date fechaInscripcion;

    public IncripcionCurso() {
    }

	
    public IncripcionCurso(int idInscripcion, Curso curso, Participante participante) {
        this.idInscripcion = idInscripcion;
        this.curso = curso;
        this.participante = participante;
    }
    public IncripcionCurso(int idInscripcion, Curso curso, Participante participante, Date fechaInscripcion) {
       this.idInscripcion = idInscripcion;
       this.curso = curso;
       this.participante = participante;
       this.fechaInscripcion = fechaInscripcion;
    }
   
     @Id 

    
    @Column(name="id_inscripcion", unique=true, nullable=false)
    public int getIdInscripcion() {
        return this.idInscripcion;
    }
    
    public void setIdInscripcion(int idInscripcion) {
        this.idInscripcion = idInscripcion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_participante", nullable=false)
    public Participante getParticipante() {
        return this.participante;
    }
    
    public void setParticipante(Participante participante) {
        this.participante = participante;
    }
    
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @Column(name="fecha_inscripcion", length=10)
    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }
    
    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }




}


