package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Local generated by hbm2java
 */
@Entity
@Table(name="local"
    ,catalog="insaforp"
)
public class Local  implements java.io.Serializable {


     private int idLocal;
     private String nombreLocal;
     private String descripcionLocal;
     private String ubicacion;
     private Integer capacidad;
     private Boolean estadoLocal;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Local() {
    }

	
    public Local(int idLocal) {
        this.idLocal = idLocal;
    }
    public Local(int idLocal, String nombreLocal, String descripcionLocal, String ubicacion, Integer capacidad, Boolean estadoLocal, Set<Curso> cursos) {
       this.idLocal = idLocal;
       this.nombreLocal = nombreLocal;
       this.descripcionLocal = descripcionLocal;
       this.ubicacion = ubicacion;
       this.capacidad = capacidad;
       this.estadoLocal = estadoLocal;
       this.cursos = cursos;
    }
   
     @Id 

    
    @Column(name="id_local", unique=true, nullable=false)
    public int getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(int idLocal) {
        this.idLocal = idLocal;
    }

    
    @Column(name="nombre_local", length=60)
    public String getNombreLocal() {
        return this.nombreLocal;
    }
    
    public void setNombreLocal(String nombreLocal) {
        this.nombreLocal = nombreLocal;
    }

    
    @Column(name="descripcion_local", length=200)
    public String getDescripcionLocal() {
        return this.descripcionLocal;
    }
    
    public void setDescripcionLocal(String descripcionLocal) {
        this.descripcionLocal = descripcionLocal;
    }

    
    @Column(name="ubicacion", length=200)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="capacidad")
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }

    
    @Column(name="estado_local")
    public Boolean getEstadoLocal() {
        return this.estadoLocal;
    }
    
    public void setEstadoLocal(Boolean estadoLocal) {
        this.estadoLocal = estadoLocal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="local")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


