package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Participante generated by hbm2java
 */
@Entity
@Table(name="participante"
    ,catalog="insaforp"
)
public class Participante  implements java.io.Serializable {


     private int idParticipante;
     private String nombreParticipante;
     private String apellidoParticipante;
     private String dui;
     private String nit;
     private Date fechaNacimiento;
     private String escolaridad;
     private String lugarTrabajo;
     private String telefonoParticipante;
     private String correoParticipante;
     private Set<IncripcionCurso> incripcionCursos = new HashSet<IncripcionCurso>(0);

    public Participante() {
    }

	
    public Participante(int idParticipante) {
        this.idParticipante = idParticipante;
    }
    public Participante(int idParticipante, String nombreParticipante, String apellidoParticipante, String dui, String nit, Date fechaNacimiento, String escolaridad, String lugarTrabajo, String telefonoParticipante, String correoParticipante, Set<IncripcionCurso> incripcionCursos) {
       this.idParticipante = idParticipante;
       this.nombreParticipante = nombreParticipante;
       this.apellidoParticipante = apellidoParticipante;
       this.dui = dui;
       this.nit = nit;
       this.fechaNacimiento = fechaNacimiento;
       this.escolaridad = escolaridad;
       this.lugarTrabajo = lugarTrabajo;
       this.telefonoParticipante = telefonoParticipante;
       this.correoParticipante = correoParticipante;
       this.incripcionCursos = incripcionCursos;
    }
   
     @Id 

    
    @Column(name="id_participante", unique=true, nullable=false)
    public int getIdParticipante() {
        return this.idParticipante;
    }
    
    public void setIdParticipante(int idParticipante) {
        this.idParticipante = idParticipante;
    }

    
    @Column(name="nombre_participante", length=50)
    public String getNombreParticipante() {
        return this.nombreParticipante;
    }
    
    public void setNombreParticipante(String nombreParticipante) {
        this.nombreParticipante = nombreParticipante;
    }

    
    @Column(name="apellido_participante", length=50)
    public String getApellidoParticipante() {
        return this.apellidoParticipante;
    }
    
    public void setApellidoParticipante(String apellidoParticipante) {
        this.apellidoParticipante = apellidoParticipante;
    }

    
    @Column(name="dui", length=10)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

    
    @Column(name="nit", length=17)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="escolaridad", length=20)
    public String getEscolaridad() {
        return this.escolaridad;
    }
    
    public void setEscolaridad(String escolaridad) {
        this.escolaridad = escolaridad;
    }

    
    @Column(name="lugar_trabajo", length=30)
    public String getLugarTrabajo() {
        return this.lugarTrabajo;
    }
    
    public void setLugarTrabajo(String lugarTrabajo) {
        this.lugarTrabajo = lugarTrabajo;
    }

    
    @Column(name="telefono_participante", length=9)
    public String getTelefonoParticipante() {
        return this.telefonoParticipante;
    }
    
    public void setTelefonoParticipante(String telefonoParticipante) {
        this.telefonoParticipante = telefonoParticipante;
    }

    
    @Column(name="correo_participante", length=20)
    public String getCorreoParticipante() {
        return this.correoParticipante;
    }
    
    public void setCorreoParticipante(String correoParticipante) {
        this.correoParticipante = correoParticipante;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="participante")
    public Set<IncripcionCurso> getIncripcionCursos() {
        return this.incripcionCursos;
    }
    
    public void setIncripcionCursos(Set<IncripcionCurso> incripcionCursos) {
        this.incripcionCursos = incripcionCursos;
    }




}


