package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Presupuesto generated by hbm2java
 */
@Entity
@Table(name="presupuesto"
    ,catalog="insaforp"
)
public class Presupuesto  implements java.io.Serializable {


     private int idPresupuesto;
     private Curso curso;
     private Date fechaCreacion;
     private Set<DetalleGasto> detalleGastos = new HashSet<DetalleGasto>(0);
     private Set<DetalleFinanciamiento> detalleFinanciamientos = new HashSet<DetalleFinanciamiento>(0);

    public Presupuesto() {
    }

	
    public Presupuesto(int idPresupuesto) {
        this.idPresupuesto = idPresupuesto;
    }
    public Presupuesto(int idPresupuesto, Curso curso, Date fechaCreacion, Set<DetalleGasto> detalleGastos, Set<DetalleFinanciamiento> detalleFinanciamientos) {
       this.idPresupuesto = idPresupuesto;
       this.curso = curso;
       this.fechaCreacion = fechaCreacion;
       this.detalleGastos = detalleGastos;
       this.detalleFinanciamientos = detalleFinanciamientos;
    }
   
     @Id 

    
    @Column(name="id_presupuesto", unique=true, nullable=false)
    public int getIdPresupuesto() {
        return this.idPresupuesto;
    }
    
    public void setIdPresupuesto(int idPresupuesto) {
        this.idPresupuesto = idPresupuesto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso")
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_creacion", length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="presupuesto")
    public Set<DetalleGasto> getDetalleGastos() {
        return this.detalleGastos;
    }
    
    public void setDetalleGastos(Set<DetalleGasto> detalleGastos) {
        this.detalleGastos = detalleGastos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="presupuesto")
    public Set<DetalleFinanciamiento> getDetalleFinanciamientos() {
        return this.detalleFinanciamientos;
    }
    
    public void setDetalleFinanciamientos(Set<DetalleFinanciamiento> detalleFinanciamientos) {
        this.detalleFinanciamientos = detalleFinanciamientos;
    }




}


