package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Programa generated by hbm2java
 */
@Entity
@Table(name="programa"
    ,catalog="insaforp"
)
public class Programa  implements java.io.Serializable {


     private int idPrograma;
     private String nombrePrograma;
     private String descripcionPrograma;
     private Boolean estadoPrograma;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Programa() {
    }

	
    public Programa(int idPrograma) {
        this.idPrograma = idPrograma;
    }
    public Programa(int idPrograma, String nombrePrograma, String descripcionPrograma, Boolean estadoPrograma, Set<Curso> cursos) {
       this.idPrograma = idPrograma;
       this.nombrePrograma = nombrePrograma;
       this.descripcionPrograma = descripcionPrograma;
       this.estadoPrograma = estadoPrograma;
       this.cursos = cursos;
    }
   
     @Id 

    
    @Column(name="id_programa", unique=true, nullable=false)
    public int getIdPrograma() {
        return this.idPrograma;
    }
    
    public void setIdPrograma(int idPrograma) {
        this.idPrograma = idPrograma;
    }

    
    @Column(name="nombre_programa", length=50)
    public String getNombrePrograma() {
        return this.nombrePrograma;
    }
    
    public void setNombrePrograma(String nombrePrograma) {
        this.nombrePrograma = nombrePrograma;
    }

    
    @Column(name="descripcion_programa", length=200)
    public String getDescripcionPrograma() {
        return this.descripcionPrograma;
    }
    
    public void setDescripcionPrograma(String descripcionPrograma) {
        this.descripcionPrograma = descripcionPrograma;
    }

    
    @Column(name="estado_programa")
    public Boolean getEstadoPrograma() {
        return this.estadoPrograma;
    }
    
    public void setEstadoPrograma(Boolean estadoPrograma) {
        this.estadoPrograma = estadoPrograma;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="programa")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


