package com.entities;
// Generated 10-28-2021 05:06:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,catalog="insaforp"
)
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String nombreProveedor;
     private String contactoProveedor;
     private String telefonoProveedor;
     private String correoProveedor;
     private Boolean estadoProveedor;
     private Boolean tipoProveedor;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Proveedor(int idProveedor, String nombreProveedor, String contactoProveedor, String telefonoProveedor, String correoProveedor, Boolean estadoProveedor, Boolean tipoProveedor, Set<Curso> cursos) {
       this.idProveedor = idProveedor;
       this.nombreProveedor = nombreProveedor;
       this.contactoProveedor = contactoProveedor;
       this.telefonoProveedor = telefonoProveedor;
       this.correoProveedor = correoProveedor;
       this.estadoProveedor = estadoProveedor;
       this.tipoProveedor = tipoProveedor;
       this.cursos = cursos;
    }
   
     @Id 

    
    @Column(name="id_proveedor", unique=true, nullable=false)
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="nombre_proveedor", length=50)
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }

    
    @Column(name="contacto_proveedor", length=30)
    public String getContactoProveedor() {
        return this.contactoProveedor;
    }
    
    public void setContactoProveedor(String contactoProveedor) {
        this.contactoProveedor = contactoProveedor;
    }

    
    @Column(name="telefono_proveedor", length=9)
    public String getTelefonoProveedor() {
        return this.telefonoProveedor;
    }
    
    public void setTelefonoProveedor(String telefonoProveedor) {
        this.telefonoProveedor = telefonoProveedor;
    }

    
    @Column(name="correo_proveedor", length=30)
    public String getCorreoProveedor() {
        return this.correoProveedor;
    }
    
    public void setCorreoProveedor(String correoProveedor) {
        this.correoProveedor = correoProveedor;
    }

    
    @Column(name="estado_proveedor")
    public Boolean getEstadoProveedor() {
        return this.estadoProveedor;
    }
    
    public void setEstadoProveedor(Boolean estadoProveedor) {
        this.estadoProveedor = estadoProveedor;
    }

    
    @Column(name="tipo_proveedor")
    public Boolean getTipoProveedor() {
        return this.tipoProveedor;
    }
    
    public void setTipoProveedor(Boolean tipoProveedor) {
        this.tipoProveedor = tipoProveedor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


